### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by iTomstudio** [euler-king/chick-element-admin#1]
![](http://ww1.sinaimg.cn/large/006bQ5mXly1gi377cvc4hj30ql0enq4m.jpg)
 
运行  npm run dev  后

提示的error

**Comment by bi-kai** [comment]
![image](https://user-images.githubusercontent.com/15070379/104452065-6bd22680-55dd-11eb-9691-fdd2c245ec3d.png)
访问时这个错你遇到没？

**Comment by iTomstudio** [comment]
我的问题和你的一样，也是唰唰唰一片path /   token undefined，，然后就报错中止了
